services:
  db:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: nishan
      POSTGRES_PASSWORD: password
      POSTGRES_DB: customer
      PGDATA: /data/postgres
    volumes:
      - db:/data/postgres
    ports:
      - "5332:5432"
    networks:
      - db
    restart: unless-stopped

  nishan-api:
    container_name: nishan-api
    image: nishan259/nishan-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/customer
    ports:
      - "8088:8080"
    networks:
      - db
    depends_on:
      - db
    restart: unless-stopped
  nishancode-react:
    container_name: nishancode-react
    image: nishan259/nishancode-react
    build:
      context:  /home/nishan/Desktop/Front-End/react
    ports:
      - "3000:5173"
    depends_on:
      - nishan-api
    restart: unless-stopped

networks:
  db:
    driver: bridge

volumes:
  db:
